// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "Refractor/domain"

	mock "github.com/stretchr/testify/mock"
)

// ClientCreator is an autogenerated mock type for the ClientCreator type
type ClientCreator struct {
	mock.Mock
}

// GetClientFromConfig provides a mock function with given fields: gameConfig, server
func (_m *ClientCreator) GetClientFromConfig(gameConfig *domain.GameConfig, server *domain.Server) (domain.RCONClient, error) {
	ret := _m.Called(gameConfig, server)

	var r0 domain.RCONClient
	if rf, ok := ret.Get(0).(func(*domain.GameConfig, *domain.Server) domain.RCONClient); ok {
		r0 = rf(gameConfig, server)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.RCONClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.GameConfig, *domain.Server) error); ok {
		r1 = rf(gameConfig, server)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
