// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "Refractor/domain"

	mock "github.com/stretchr/testify/mock"
)

// GameService is an autogenerated mock type for the GameService type
type GameService struct {
	mock.Mock
}

// AddGame provides a mock function with given fields: game
func (_m *GameService) AddGame(game domain.Game) {
	_m.Called(game)
}

// GameExists provides a mock function with given fields: name
func (_m *GameService) GameExists(name string) bool {
	ret := _m.Called(name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetAllGames provides a mock function with given fields:
func (_m *GameService) GetAllGames() []domain.Game {
	ret := _m.Called()

	var r0 []domain.Game
	if rf, ok := ret.Get(0).(func() []domain.Game); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Game)
		}
	}

	return r0
}

// GetGame provides a mock function with given fields: name
func (_m *GameService) GetGame(name string) (domain.Game, error) {
	ret := _m.Called(name)

	var r0 domain.Game
	if rf, ok := ret.Get(0).(func(string) domain.Game); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Game)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
