// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "Refractor/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ServerService is an autogenerated mock type for the ServerService type
type ServerService struct {
	mock.Mock
}

// Deactivate provides a mock function with given fields: c, id
func (_m *ServerService) Deactivate(c context.Context, id int64) error {
	ret := _m.Called(c, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: c
func (_m *ServerService) GetAll(c context.Context) ([]*domain.Server, error) {
	ret := _m.Called(c)

	var r0 []*domain.Server
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Server); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Server)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: c, id
func (_m *ServerService) GetByID(c context.Context, id int64) (*domain.Server, error) {
	ret := _m.Called(c, id)

	var r0 *domain.Server
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Server); ok {
		r0 = rf(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Server)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: c, server
func (_m *ServerService) Store(c context.Context, server *domain.Server) error {
	ret := _m.Called(c, server)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Server) error); ok {
		r0 = rf(c, server)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
