// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "Refractor/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AttachmentService is an autogenerated mock type for the AttachmentService type
type AttachmentService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: c, id
func (_m *AttachmentService) Delete(c context.Context, id int64) error {
	ret := _m.Called(c, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByInfraction provides a mock function with given fields: c, infractionID
func (_m *AttachmentService) GetByInfraction(c context.Context, infractionID int64) ([]*domain.Attachment, error) {
	ret := _m.Called(c, infractionID)

	var r0 []*domain.Attachment
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*domain.Attachment); ok {
		r0 = rf(c, infractionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Attachment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(c, infractionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: c, attachment
func (_m *AttachmentService) Store(c context.Context, attachment *domain.Attachment) error {
	ret := _m.Called(c, attachment)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Attachment) error); ok {
		r0 = rf(c, attachment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
