// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "Refractor/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: c, userTraits, inviter
func (_m *AuthService) CreateUser(c context.Context, userTraits *domain.Traits, inviter string) (*domain.AuthUser, error) {
	ret := _m.Called(c, userTraits, inviter)

	var r0 *domain.AuthUser
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Traits, string) *domain.AuthUser); ok {
		r0 = rf(c, userTraits, inviter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthUser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Traits, string) error); ok {
		r1 = rf(c, userTraits, inviter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
