// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "Refractor/domain"

	mock "github.com/stretchr/testify/mock"
)

// RCONService is an autogenerated mock type for the RCONService type
type RCONService struct {
	mock.Mock
}

// CreateClient provides a mock function with given fields: server
func (_m *RCONService) CreateClient(server *domain.Server) error {
	ret := _m.Called(server)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Server) error); ok {
		r0 = rf(server)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteClient provides a mock function with given fields: serverID
func (_m *RCONService) DeleteClient(serverID int64) {
	_m.Called(serverID)
}

// GetClients provides a mock function with given fields:
func (_m *RCONService) GetClients() map[int64]domain.RCONClient {
	ret := _m.Called()

	var r0 map[int64]domain.RCONClient
	if rf, ok := ret.Get(0).(func() map[int64]domain.RCONClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]domain.RCONClient)
		}
	}

	return r0
}

// GetServerClient provides a mock function with given fields: serverID
func (_m *RCONService) GetServerClient(serverID int64) domain.RCONClient {
	ret := _m.Called(serverID)

	var r0 domain.RCONClient
	if rf, ok := ret.Get(0).(func(int64) domain.RCONClient); ok {
		r0 = rf(serverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.RCONClient)
		}
	}

	return r0
}

// HandleServerUpdate provides a mock function with given fields: server
func (_m *RCONService) HandleServerUpdate(server *domain.Server) {
	_m.Called(server)
}

// RefreshPlayerList provides a mock function with given fields: serverID, game
func (_m *RCONService) RefreshPlayerList(serverID int64, game domain.Game) error {
	ret := _m.Called(serverID, game)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, domain.Game) error); ok {
		r0 = rf(serverID, game)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendChatMessage provides a mock function with given fields: body
func (_m *RCONService) SendChatMessage(body *domain.ChatSendBody) {
	_m.Called(body)
}

// StartReconnectRoutine provides a mock function with given fields: serverID, data
func (_m *RCONService) StartReconnectRoutine(serverID int64, data *domain.ServerData) {
	_m.Called(serverID, data)
}

// SubscribeChat provides a mock function with given fields: sub
func (_m *RCONService) SubscribeChat(sub domain.ChatReceiveSubscriber) {
	_m.Called(sub)
}

// SubscribeJoin provides a mock function with given fields: sub
func (_m *RCONService) SubscribeJoin(sub domain.BroadcastSubscriber) {
	_m.Called(sub)
}

// SubscribeModeratorAction provides a mock function with given fields: sub
func (_m *RCONService) SubscribeModeratorAction(sub domain.BroadcastSubscriber) {
	_m.Called(sub)
}

// SubscribePlayerListUpdate provides a mock function with given fields: sub
func (_m *RCONService) SubscribePlayerListUpdate(sub domain.PlayerListUpdateSubscriber) {
	_m.Called(sub)
}

// SubscribeQuit provides a mock function with given fields: sub
func (_m *RCONService) SubscribeQuit(sub domain.BroadcastSubscriber) {
	_m.Called(sub)
}

// SubscribeServerStatus provides a mock function with given fields: sub
func (_m *RCONService) SubscribeServerStatus(sub domain.ServerStatusSubscriber) {
	_m.Called(sub)
}
