name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working_directory: "./src"
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        working-directory: ${{env.working_directory}}
        run: go build main.go

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        working-directory: ${{env.working_directory}}
        run: go test ./src/... -v
